- name: copy docker-compose file
 template:
   src: docker-compose.yml
   dest: "{{TARGET_PATH}}/docker-compose.yml"

- name: raise container
  shell: docekr-compose -f {{TARGET_PATH}}/docker-compose.yml up -d



