  - name: rm old packer
    shell: rm -rf /usr/local/tomcat/webapps/OTO_22COIN*

  - name: copy package
    copy: src=/home/pack/OTO_22COIN_V1.war dest=/usr/local/tomcat/webapps/

  - name: the status of tomcat
    shell: netstat -ntlp |grep 8080|awk '{print $4}'|awk -F ':' '{print $4}'
    register: info

  - name: stop tomcat
    shell: netstat  -ntlp|grep 8080|awk '{print $7}'|cut -d'/' -f1 |xargs kill -9
    when: info['stdout']=="8080"

  - name: start tomcat
    shell: chdir=/usr/local/tomcat/bin nohup ./catalina.sh start &
