version: '2'
services:
    gitlab:
      image: 'gitlab/gitlab-ce'    #twang2218/gitlab-ce-zh:latest
      restart: always
      hostname: 'gitlab.qxx.org'
      ports: 
          - "8080:80"
          - "8443:443"
          - "2222:22"
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://ip:port'
           gitlab_rails['smtp_port'] = 25
           gitlab_rails['smtp_address'] = "smtp.163.com"
           gitlab_rails['smtp_user_name'] = "hjyqxx@163.com"
           gitlab_rails['smtp_password'] = "qxx517"
           gitlab_rails['smtp_domain'] = "163.com"
           gitlab_rails['smtp_authentication'] = "login"
           gitlab_rails['smtp_enable_starttls_auto'] = true
           gitlab_rails['smtp_tls'] = false
           gitlab_rails['smtp_openssl_verify_mode'] = 'none'
           gitlab_rails['gitlab_email_from'] = "hjyqxx@163.com"
           user['git_user_email'] = "hjyqxx@163.com"
           gitlab_rails['time_zone'] = 'Asia/Shanghai'
           nginx['listen_port'] = 80
           gitlab_rails['gitlab_ssh_host'] = '218.17.30.25'
           gitlab_rails['gitlab_shell_ssh_port'] = 3333

      volumes:
        - /docker/volume/gitlab/config:/etc/gitlab
        - /docker/volume/gitlab/data:/var/opt/gitlab
        - /docker/volume/gitlab/logs:/var/log/gitlab
      networks:
           gitlab_net:
 networks:
     gitlab_net:

