- name: install jdk
  copy: src={{ jdk_path }}  dest={{ jdk_dest_path }}

- name: set jdk env
  templates: src=jdk.sh  dest=/etc/profile.d/

- name: source jdk_env
  shell: /etc/profile.d/jdk.sh

#- name: absent old tomcat
#      file: path={{ item }} state=absent
#      with_items:
#        - "{{ tomcat_home }}"
#        - /geelyapp/auto_scripts/tomcat.sh
- name: get tomcat_tar_gz
      get_url: url={{ tomcat_url }} dest=/tmp/tomcat.tar.gz

#    - name: Create the dir
#      file: path={{ item }} state=directory
#      with_items:
#        - /geelyapp/gc_log
#        - /geelyapp/auto_scripts
#        - "{{ tomcat_home }}"
- name: tar xzf tomcat_tar_gz
  unarchive: src=/tmp/tomcat.tar.gz  dest={{ tomcat_home }}/tomcat copy=no

- name: init server.xml
  template: src=server.xml dest={{ tomcat_home }}/tomcat/conf/server.xml
#    - name: init setenv.sh
#      template: src=/ansible/roles/tomcat/templates/setenv.sh.j2 dest={{ tomcat_home }}/bin/setenv.sh mode=0755
#    - name: init the tomcat maintain script
#      template: src=/ansible/roles/tomcat/templates/tomcat.sh.j2 dest=/geelyapp/auto_scripts/tomcat.sh owner={{ user|default('root') }} group={{ user|default('root') }} mode=0755
#    - name: rename the tomcat scripts
#      shell: mv /geelyapp/auto_scripts/tomcat.sh /geelyapp/auto_scripts/`echo "{{ tomcat_home }}" |awk -F "/" '{print $3}'`.sh
#    - name: change owner tomcat and scripts to {{ user|default('root') }}
#      file: path={{ tomcat_home }} owner={{ user|default('root') }} group={{ user|default('root') }} recurse=yes
#      ignore_errors: yes
