version: '2'
services:
  cockroach:
    image: cockroachdb/cockroach:v1.1.3
    hostname: roach1
    networks:
      - cr0
    restart: unless-stopped
    ports:
      - 8080
    command: "start --insecure"

networks:
  cr0:
    driver: overlay
