version: '2'
services:
    registry:
        image: registry:2.6.1
        hostname: registry
        ports:
            - 443:5000/tcp
        networks:
            registry:
                aliases:
                    - registry
        volumes:
            - /var/lib/registry:/var/lib/registry:rw
            - /home/certs:/certs
        environment:
            - REGISTRY_HTTP_TLS_KEY=/certs/gcr.io.key
            - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/gcr.io.crt
networks:
    registry:
        external: true

# Registry主机
# openssl req -newkey rsa:4096 -nodes -sha256 -keyout hub.xmitd.com.key -x509 -days 365 -out hub.xmitd.com.crt
# Client主机
# mkdir -p /etc/docker/certs.d/hub.xmitd.com
# /home/certs/hub.xmitd.com.crt是registry主机生成的
# cp /home/certs/hub.xmitd.com.crt /etc/docker/certs.d/hub.xmitd.com/
