version: '2'
services:
    zookeeper01:
        image: daocloud.io/buxiaomo/zookeeper
        ports:
            - 8004:2181/tcp
        environment:
            - ZOOKEEPER_ID=1
            - ZOOKEEPER_CLUSTER=server.1=zookeeper01:2888:3888,server.2=zookeeper02:2888:3888,server.3=zookeeper03:2888:3888
        networks:
            kafka:
                aliases:
                    - zookeeper01
    zookeeper02:
        image: daocloud.io/buxiaomo/zookeeper
        ports:
            - 8005:2181/tcp
        environment:
            - ZOOKEEPER_ID=2
            - ZOOKEEPER_CLUSTER=server.1=zookeeper01:2888:3888,server.2=zookeeper02:2888:3888,server.3=zookeeper03:2888:3888
        networks:
            kafka:
                aliases:
                    - zookeeper02
    zookeeper03:
        image: daocloud.io/buxiaomo/zookeeper
        ports:
            - 8006:2181/tcp
        environment:
            - ZOOKEEPER_ID=3
            - ZOOKEEPER_CLUSTER=server.1=zookeeper01:2888:3888,server.2=zookeeper02:2888:3888,server.3=zookeeper03:2888:3888
        networks:
            kafka:
                aliases:
                    - zookeeper03
networks:
    kafka:
        external: true
